theme = 'ananke'

enableRobotsTXT = true
Paginate = 10

[languages]
  [languages.en]
    baseURL = 'https://little-railways.com/'
    languageName = 'English'
    title = 'My little railways'
  [languages.es]
    baseURL = 'https://little-railways.es'
    languageName = 'Español'
    title = 'My little railways'

[sitemap]
  changefreq = "daily"
  priority = 0.5
  filename = "sitemap.xml"